import type { DemoPatient } from './types'

// Fake demo data only. Do not replace these records with real patient data.
export const demoPatients: DemoPatient[] = [
  {
    id: 'demo-patient-001',
    firstName: 'Ana',
    lastName: 'Demo',
    phone: '+381 60 000 0001',
    email: 'ana.demo@example.test',
    dateOfBirth: '1988-04-12',
    status: 'active',
    nextAppointment: '2026-05-14T09:30:00',
    lastVisit: '2026-04-29',
    activeTreatmentPlan: 'Demo restorative plan',
    importantNote: 'Demo allergy warning',
    unpaidBalance: 12000,
    medicalWarnings: [
      'Demo medical warning - verify before treatment',
      'Demo allergy warning',
    ],
    anamnesisSummary: 'Demo anamnesis summary for UI testing only.',
    allergies: 'Demo allergy warning.',
    currentMedications: 'Demo medication entry for local testing.',
    dentalHistorySummary: 'Demo dental history note for profile layout testing.',
    riskNotes: 'Demo risk note for UI testing only.',
    lastClinicalNote: 'Demo clinical note summary. No real clinical data.',
    activeTreatmentPlanSummary:
      'Demo treatment plan summary for restorative follow-up.',
    nextRecommendedStep: 'Demo next step - review plan before next visit.',
    recentVisitSummary: 'Demo recent visit recorded for UI foundation testing.',
    documentsCount: 2,
    timelineEvents: [
      {
        id: 'demo-patient-001-event-001',
        label: 'Demo appointment created',
        date: '2026-05-10',
        description: 'Fake timeline event for scheduling context.',
      },
      {
        id: 'demo-patient-001-event-002',
        label: 'Demo treatment plan updated',
        date: '2026-04-29',
        description: 'Fake timeline event for treatment planning context.',
      },
    ],
  },
  {
    id: 'demo-patient-002',
    firstName: 'Marko',
    lastName: 'Test',
    phone: '+381 60 000 0002',
    email: 'marko.test@example.test',
    dateOfBirth: '1979-11-02',
    status: 'active',
    nextAppointment: null,
    lastVisit: '2026-05-02',
    activeTreatmentPlan: 'Demo implant consultation',
    importantNote: null,
    unpaidBalance: 0,
    medicalWarnings: [],
    anamnesisSummary: 'Demo anamnesis summary for UI testing only.',
    allergies: '',
    currentMedications: '',
    dentalHistorySummary: 'Demo dental history note for consultation context.',
    riskNotes: '',
    lastClinicalNote: 'Demo clinical note summary. No real clinical data.',
    activeTreatmentPlanSummary:
      'Demo treatment plan summary for consultation review.',
    nextRecommendedStep: 'Demo next step - schedule follow-up if needed.',
    recentVisitSummary: 'Demo recent visit recorded for profile testing.',
    documentsCount: 0,
    timelineEvents: [
      {
        id: 'demo-patient-002-event-001',
        label: 'Demo visit recorded',
        date: '2026-05-02',
        description: 'Fake timeline event for visit context.',
      },
      {
        id: 'demo-patient-002-event-002',
        label: 'Demo payment recorded',
        date: '2026-05-02',
        description: 'Fake timeline event for payment context.',
      },
    ],
  },
  {
    id: 'demo-patient-003',
    firstName: 'Jelena',
    lastName: 'Primer',
    phone: '+381 60 000 0003',
    email: 'jelena.primer@example.test',
    dateOfBirth: '1992-07-18',
    status: 'inactive',
    nextAppointment: null,
    lastVisit: '2026-03-21',
    activeTreatmentPlan: null,
    importantNote: 'Demo medical note',
    unpaidBalance: 5000,
    medicalWarnings: ['Demo medical note - confirm before treatment'],
    anamnesisSummary: 'Demo anamnesis summary for inactive profile testing.',
    allergies: '',
    currentMedications: '',
    dentalHistorySummary: 'Demo dental history note for read-only display.',
    riskNotes: 'Demo follow-up risk note.',
    lastClinicalNote: 'Demo clinical note summary. No real clinical data.',
    activeTreatmentPlanSummary: 'No active demo treatment plan.',
    nextRecommendedStep: 'Demo next step - confirm patient status.',
    recentVisitSummary: 'Demo older visit summary for UI testing.',
    documentsCount: 1,
    timelineEvents: [
      {
        id: 'demo-patient-003-event-001',
        label: 'Demo treatment plan updated',
        date: '2026-03-21',
        description: 'Fake timeline event for inactive patient context.',
      },
    ],
  },
  {
    id: 'demo-patient-004',
    firstName: 'Nikola',
    lastName: 'Uzorak',
    phone: '+381 60 000 0004',
    email: 'nikola.uzorak@example.test',
    dateOfBirth: '1984-01-30',
    status: 'archived',
    nextAppointment: null,
    lastVisit: '2025-12-10',
    activeTreatmentPlan: null,
    importantNote: null,
    unpaidBalance: 0,
    medicalWarnings: [],
    anamnesisSummary: 'Demo archived anamnesis summary for UI testing only.',
    allergies: '',
    currentMedications: '',
    dentalHistorySummary: 'Demo archived dental history note.',
    riskNotes: '',
    lastClinicalNote: 'Demo archived clinical note summary.',
    activeTreatmentPlanSummary: 'No active demo treatment plan.',
    nextRecommendedStep: 'Demo next step - archived profile review only.',
    recentVisitSummary: 'Demo archived visit summary for UI testing.',
    documentsCount: 0,
    timelineEvents: [
      {
        id: 'demo-patient-004-event-001',
        label: 'Demo profile archived',
        date: '2025-12-10',
        description: 'Fake timeline event for archived patient context.',
      },
    ],
  },
  {
    id: 'demo-patient-005',
    firstName: 'Milica',
    lastName: 'Fiktivna',
    phone: '+381 60 000 0005',
    email: 'milica.fiktivna@example.test',
    dateOfBirth: '1995-09-05',
    status: 'active',
    nextAppointment: '2026-05-16T13:00:00',
    lastVisit: '2026-04-12',
    activeTreatmentPlan: 'Demo orthodontic review',
    importantNote: null,
    unpaidBalance: 18000,
    medicalWarnings: [],
    anamnesisSummary: 'Demo anamnesis summary for UI testing only.',
    allergies: '',
    currentMedications: '',
    dentalHistorySummary: 'Demo dental history note for orthodontic context.',
    riskNotes: '',
    lastClinicalNote: 'Demo clinical note summary. No real clinical data.',
    activeTreatmentPlanSummary:
      'Demo treatment plan summary for orthodontic review.',
    nextRecommendedStep: 'Demo next step - review progress at next visit.',
    recentVisitSummary: 'Demo recent visit recorded for treatment context.',
    documentsCount: 3,
    timelineEvents: [
      {
        id: 'demo-patient-005-event-001',
        label: 'Demo appointment created',
        date: '2026-05-10',
        description: 'Fake timeline event for appointment context.',
      },
      {
        id: 'demo-patient-005-event-002',
        label: 'Demo visit recorded',
        date: '2026-04-12',
        description: 'Fake timeline event for visit context.',
      },
    ],
  },
]

export function findDemoPatientById(patientId: string | undefined) {
  return demoPatients.find((patient) => patient.id === patientId)
}
